import { useCallback, useEffect, useState } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import { useNavigate } from 'react-router-dom';
import { logout } from '../store/slices/authSlice';
import { activityApi, clientApi, companyApi, contactApi, dealApi, invoiceApi, leadApi, milestoneApi, portalApi, projectApi, prospectApi, requirementApi, taskApi, ticketApi, userApi } from '../api';
import { DocumentsPage, PaymentsPage, QuotationsPage, RequirementVaultPage, TaskWorkspacePage, TicketConversationPage } from './VaultPages';
import './DashboardPage.css';
import './Crud.css';
import './Overview.css';
import './Responsive.css';

const items = [['dashboard', 'Dashboard'], ['portal', 'Client Portal'], ['companies', 'Companies'], ['clients', 'Clients'], ['contacts', 'Contacts'], ['prospects', 'Prospects'], ['activities', 'Activities'], ['leads', 'Leads'], ['deals', 'Deals'], ['projects', 'Projects'], ['milestones', 'Milestones'], ['tasks', 'Tasks'], ['taskwork', 'Task Workspace'], ['requirements', 'Requirement Vault'], ['documents', 'Documents'], ['invoices', 'Invoices'], ['payments', 'Payments'], ['quotations', 'Quotations'], ['tickets', 'Support Tickets'], ['messages', 'Ticket Conversations'], ['users', 'Users']];
const pages = {
  companies: { title: 'Companies', singular: 'Company', api: companyApi, columns: [['name', 'Name'], ['industry', 'Industry'], ['website', 'Website'], ['phone', 'Phone'], ['address', 'Address']], fields: [['name', 'Name', 'text', true], ['industry', 'Industry', 'text', false], ['website', 'Website', 'url', false], ['address', 'Address', 'textarea', false], ['phone', 'Phone', 'text', false]] },
  clients: { title: 'Clients', singular: 'Client', api: clientApi, columns: [['Company.name', 'Company'], ['status', 'Status'], ['portalAccess', 'Portal access'], ['createdAt', 'Created']], fields: [['companyId', 'Company ID', 'number', true], ['accountManagerId', 'Account manager ID', 'number', false], ['billingInfo', 'Billing information', 'textarea', false], ['status', 'Status', 'select', false, ['active', 'inactive', 'suspended']], ['portalAccess', 'Portal access', 'checkbox', false]] },
  contacts: { title: 'Contacts', singular: 'Contact', api: contactApi, columns: [['name', 'Name'], ['role', 'Role'], ['email', 'Email'], ['phone', 'Phone'], ['isPrimary', 'Primary']], fields: [['name', 'Name', 'text', true], ['companyId', 'Company ID', 'number', false], ['clientId', 'Client ID', 'number', false], ['role', 'Role', 'text', false], ['email', 'Email', 'email', false], ['phone', 'Phone', 'text', false], ['isPrimary', 'Primary contact', 'checkbox', false], ['notes', 'Notes', 'textarea', false]] },
  prospects: { title: 'Prospects', singular: 'Prospect', api: prospectApi, columns: [['companyId', 'Company ID'], ['contactId', 'Contact ID'], ['status', 'Status'], ['value', 'Value'], ['probability', 'Probability']], fields: [['companyId', 'Company ID', 'number', true], ['contactId', 'Contact ID', 'number', false], ['requirementSummary', 'Requirement summary', 'textarea', false], ['value', 'Value', 'number', false], ['probability', 'Probability', 'number', false], ['status', 'Status', 'select', false, ['new', 'qualified', 'follow_up', 'converted', 'lost']], ['nextFollowUp', 'Next follow-up', 'date', false], ['ownerId', 'Owner ID', 'number', false]] },
  activities: { title: 'Activities', singular: 'Activity', api: activityApi, columns: [['type', 'Type'], ['subject', 'Subject'], ['activityDate', 'Date'], ['relatedType', 'Related type'], ['notes', 'Notes']], fields: [['type', 'Type', 'select', true, ['call', 'email', 'meeting', 'note', 'follow_up']], ['subject', 'Subject', 'text', true], ['activityDate', 'Date', 'date', false], ['ownerId', 'Owner ID', 'number', true], ['relatedType', 'Related type', 'text', false], ['relatedId', 'Related ID', 'number', false], ['notes', 'Notes', 'textarea', false]] },
  users: { title: 'Users', singular: 'User', api: userApi, columns: [['name', 'Name'], ['email', 'Email'], ['role.name', 'Role'], ['status', 'Status']], fields: [['name', 'Name', 'text', true], ['email', 'Email', 'email', true], ['password', 'Password', 'password', false], ['roleId', 'Role ID', 'number', true], ['status', 'Status', 'select', false, ['active', 'inactive', 'suspended']]] },
  leads: { title: 'Leads', api: leadApi, columns: [['name', 'Name'], ['email', 'Email'], ['phone', 'Phone'], ['status', 'Status'], ['score', 'Score']], fields: [['companyId', 'Company ID', 'number', true], ['name', 'Name', 'text', true], ['email', 'Email', 'email', true], ['phone', 'Phone', 'text', true], ['source', 'Source', 'select', true, ['website', 'referral', 'cold_call', 'social_media', 'other']], ['status', 'Status', 'select', false, ['new', 'contacted', 'qualified', 'lost']], ['score', 'Score', 'number', false]] },
  deals: { title: 'Deals', api: dealApi, columns: [['title', 'Title'], ['stage', 'Stage'], ['value', 'Value'], ['probability', 'Probability'], ['expectedClose', 'Expected close']], fields: [['title', 'Title', 'text', true], ['companyId', 'Company ID', 'number', true], ['leadId', 'Lead ID', 'number', false], ['stage', 'Stage', 'select', true, ['new_lead', 'contacted', 'qualified', 'proposal_sent', 'negotiation', 'won', 'lost']], ['value', 'Value', 'number', true], ['probability', 'Probability', 'number', false], ['expectedClose', 'Expected close', 'date', false]] },
  projects: { title: 'Projects', api: projectApi, columns: [['code', 'Code'], ['name', 'Name'], ['status', 'Status'], ['startDate', 'Start date'], ['endDate', 'End date']], fields: [['code', 'Code', 'text', true], ['name', 'Name', 'text', true], ['description', 'Description', 'textarea', false], ['clientId', 'Client ID', 'number', true], ['pmId', 'Project manager ID', 'number', true], ['status', 'Status', 'select', false, ['planning', 'active', 'on_hold', 'in_review', 'uat', 'completed', 'archived']], ['startDate', 'Start date', 'date', true], ['endDate', 'End date', 'date', false], ['budget', 'Budget', 'number', false]] },
  milestones: { title: 'Milestones', singular: 'Milestone', api: milestoneApi, columns: [['projectId', 'Project ID'], ['name', 'Name'], ['status', 'Status'], ['progress', 'Progress'], ['dueDate', 'Due date']], fields: [['projectId', 'Project ID', 'number', true], ['name', 'Name', 'text', true], ['description', 'Description', 'textarea', false], ['dueDate', 'Due date', 'date', false], ['status', 'Status', 'select', false, ['planned', 'in_progress', 'completed', 'blocked']], ['progress', 'Progress', 'number', false]] },
  tasks: { title: 'Tasks', singular: 'Task', api: taskApi, columns: [['title', 'Title'], ['project.name', 'Project'], ['status', 'Status'], ['priority', 'Priority'], ['dueDate', 'Due date']], fields: [['projectId', 'Project ID', 'number', true], ['title', 'Title', 'text', true], ['description', 'Description', 'textarea', false], ['assigneeId', 'Assignee ID', 'number', false], ['status', 'Status', 'select', false, ['todo', 'in_progress', 'review', 'done']], ['priority', 'Priority', 'select', false, ['low', 'medium', 'high', 'critical']], ['dueDate', 'Due date', 'date', false]] },
  requirements: { title: 'Requirements', api: requirementApi, columns: [['code', 'Code'], ['title', 'Title'], ['priority', 'Priority'], ['status', 'Status'], ['currentVersion', 'Version']], fields: [['projectId', 'Project ID', 'number', true], ['title', 'Title', 'text', true], ['description', 'Description', 'textarea', true], ['priority', 'Priority', 'select', false, ['low', 'medium', 'high', 'critical']], ['status', 'Status', 'select', false, ['draft', 'submitted', 'clarification', 'approved', 'rejected', 'implemented']]] },
  invoices: { title: 'Invoices', api: invoiceApi, columns: [['number', 'Number'], ['amount', 'Amount'], ['status', 'Status'], ['issueDate', 'Issue date'], ['dueDate', 'Due date']], fields: [['clientId', 'Client ID', 'number', true], ['projectId', 'Project ID', 'number', false], ['amount', 'Amount', 'number', true], ['status', 'Status', 'select', false, ['draft', 'sent', 'partially_paid', 'paid', 'overdue', 'cancelled']], ['issueDate', 'Issue date', 'date', true], ['dueDate', 'Due date', 'date', true], ['description', 'Description', 'textarea', false]] },
  tickets: { title: 'Support Tickets', api: ticketApi, columns: [['number', 'Number'], ['title', 'Subject'], ['priority', 'Priority'], ['status', 'Status'], ['createdAt', 'Created']], fields: [['projectId', 'Project ID', 'number', true], ['clientId', 'Client ID', 'number', true], ['title', 'Subject', 'text', true], ['description', 'Description', 'textarea', true], ['priority', 'Priority', 'select', false, ['low', 'medium', 'high', 'urgent']], ['status', 'Status', 'select', false, ['open', 'in_progress', 'pending', 'resolved', 'closed']], ['assignedTo', 'Assigned user ID', 'number', false]] },
};
const valueAt = (record, path) => path.split('.').reduce((value, key) => value?.[key], record);
const display = (value, key) => { if (value == null || value === '') return '—'; if (key === 'amount' || key === 'value') return `$${Number(value).toLocaleString()}`; if (key === 'score' || key === 'probability') return `${value}%`; if (key.toLowerCase().includes('date') || key === 'createdAt') return new Date(value).toLocaleDateString(); return String(value).replaceAll('_', ' '); };

function Editor({ page, record, onClose, onSaved }) {
  const [form, setForm] = useState(() => Object.fromEntries(page.fields.map(([key, , type]) => [key, record?.[key] ?? (type === 'checkbox' ? false : '')]))); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(''); const payload = Object.fromEntries(Object.entries(form).filter(([, value]) => value !== '').map(([key, value]) => { const field = page.fields.find(([name]) => name === key); return [key, field?.[2] === 'number' ? Number(value) : value]; })); try { if (record) await page.api.update(record.id, payload); else await page.api.create(payload); onSaved(); onClose(); } catch (err) { setError(err.response?.data?.message || 'Could not save this record.'); } finally { setSaving(false); } };
  const singular = page.singular || page.title.slice(0, -1);
  return <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><form className="edit-modal" onSubmit={submit}><div className="modal-header"><div><span className="page-kicker">{record ? 'Edit record' : 'New record'}</span><h2>{record ? `Edit ${singular}` : `Create ${singular}`}</h2></div><button type="button" className="modal-close" onClick={onClose}>Close</button></div>{error && <div className="records-error">{error}</div>}<div className="form-grid">{page.fields.map(([key, label, type, required, options]) => <label key={key}>{label}{required && ' *'}{type === 'select' ? <select required={required} value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })}><option value="">Select {label}</option>{options.map((option) => <option key={option} value={option}>{option.replaceAll('_', ' ')}</option>)}</select> : type === 'textarea' ? <textarea required={required} value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} /> : type === 'checkbox' ? <input type="checkbox" checked={Boolean(form[key])} onChange={(event) => setForm({ ...form, [key]: event.target.checked })} /> : <input required={required} type={type} value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} />}</label>)}</div><div className="modal-actions"><button type="button" className="secondary-action" onClick={onClose}>Cancel</button><button type="submit" className="page-action" disabled={saving}>{saving ? 'Saving...' : 'Save record'}</button></div></form></div>;
}

function RecordsPage({ pageKey }) {
  const page = pages[pageKey]; const [records, setRecords] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [editor, setEditor] = useState(null);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const result = await page.api.getAll({ limit: 50 }); setRecords(result.data || []); } catch (err) { setError(err.response?.data?.message || 'Could not load records.'); } finally { setLoading(false); } }, [page]);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  const remove = async (record) => { if (!window.confirm(`Delete this ${page.title.slice(0, -1).toLowerCase()}?`)) return; try { await page.api.delete(record.id); await load(); } catch (err) { setError(err.response?.data?.message || 'Could not delete this record.'); } };
  const singular = page.singular || page.title.slice(0, -1);
  return <div className="records-page"><div className="page-heading"><div><span className="page-kicker">Workspace / {page.title}</span><h1>{page.title}</h1><p>Review, create, edit, and delete {page.title.toLowerCase()}.</p></div><div className="page-actions"><button className="secondary-action" onClick={load}>↻ Refresh</button><button className="page-action" onClick={() => setEditor({})}>＋ New {singular}</button></div></div><div className="records-card">{error && <div className="records-error">{error}</div>}{loading ? <div className="records-state">Loading...</div> : records.length === 0 ? <div className="records-state"><strong>No records found</strong><span>Use the New button to create the first record.</span></div> : <div className="table-scroll"><table><thead><tr>{page.columns.map(([, heading]) => <th key={heading}>{heading}</th>)}<th>Actions</th></tr></thead><tbody>{records.map((record) => <tr key={record.id || record.number}>{page.columns.map(([key]) => { const raw = valueAt(record, key); const isStatus = ['status', 'stage', 'priority'].includes(key); return <td key={key}>{isStatus ? <span className={`record-status ${String(raw).toLowerCase().replaceAll('_', '-')}`}>{display(raw, key)}</span> : display(raw, key)}</td>; })}<td className="row-actions"><button onClick={() => setEditor(record)}>Edit</button><button onClick={() => remove(record)}>Delete</button></td></tr>)}</tbody></table></div>}</div>{editor && <Editor page={page} record={editor.id ? editor : null} onClose={() => setEditor(null)} onSaved={load} />}</div>;
}

function OverviewList({ title, records, type, onOpen }) {
  return <div className="overview-panel"><div className="overview-panel-header"><h2>{title}</h2><button onClick={() => onOpen(type)}>View all →</button></div>{records.length === 0 ? <p className="overview-empty">No records available.</p> : <div className="overview-records">{records.slice(0, 4).map((record) => <button className="overview-record" key={record.id || record.number} onClick={() => onOpen(type)}><span><strong>{record.name || record.title || record.number || record.code}</strong><small>{record.email || record.stage || record.status || record.priority || 'Record'}</small></span><span className="overview-arrow">→</span></button>)}</div>}</div>;
}

function HomePage({ user }) {
  const [data, setData] = useState({ leads: [], deals: [], projects: [], tickets: [] });
  useEffect(() => { Promise.all([leadApi.getAll({ limit: 4 }), dealApi.getAll({ limit: 4 }), projectApi.getAll({ limit: 4 }), ticketApi.getAll({ limit: 4 })]).then(([leads, deals, projects, tickets]) => setData({ leads: leads.data || [], deals: deals.data || [], projects: projects.data || [], tickets: tickets.data || [] })).catch(() => {}); }, []);
  const open = (type) => { window.location.hash = `#/${type}`; };
  return <div className="records-page"><div className="page-heading"><div><span className="page-kicker">DevFlow CRM / Overview</span><h1>Welcome, {user?.name || 'User'}!</h1><p>Your latest CRM activity at a glance.</p></div></div><div className="dashboard-grid"><div className="card"><h3>Leads</h3><p className="stat-number">{data.leads.length}</p><p className="stat-label">Latest records</p></div><div className="card"><h3>Deals</h3><p className="stat-number">{data.deals.length}</p><p className="stat-label">Latest records</p></div><div className="card"><h3>Projects</h3><p className="stat-number">{data.projects.length}</p><p className="stat-label">Latest records</p></div><div className="card"><h3>Tickets</h3><p className="stat-number">{data.tickets.length}</p><p className="stat-label">Latest records</p></div></div><div className="overview-panels"><OverviewList title="Recent Leads" records={data.leads} type="leads" onOpen={open} /><OverviewList title="Recent Deals" records={data.deals} type="deals" onOpen={open} /><OverviewList title="Active Projects" records={data.projects} type="projects" onOpen={open} /><OverviewList title="Support Tickets" records={data.tickets} type="tickets" onOpen={open} /></div></div>;
}

function DealsPipeline() {
  const stages = ['new_lead', 'contacted', 'qualified', 'proposal_sent', 'negotiation', 'won', 'lost'];
  const [pipeline, setPipeline] = useState([]); const [error, setError] = useState('');
  const load = useCallback(async () => { try { const result = await dealApi.getPipeline(); setPipeline(result.data || []); } catch (err) { setError(err.response?.data?.message || 'Could not load pipeline.'); } }, []);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  const move = async (deal, stage) => { try { await dealApi.update(deal.id, { stage }); await load(); } catch (err) { setError(err.response?.data?.message || 'Could not move deal.'); } };
  const columns = Object.fromEntries(pipeline.map((column) => [column.stage, column.deals]));
  return <div className="records-page"><div className="page-heading"><div><span className="page-kicker">Workspace / Pipeline</span><h1>Deal Pipeline</h1><p>Drag a deal into another stage to update its forecast.</p></div><button className="secondary-action" onClick={load}>Refresh</button></div>{error && <div className="records-error">{error}</div>}<div className="pipeline-board">{stages.map((stage) => <section className="pipeline-column" key={stage} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { const deal = JSON.parse(event.dataTransfer.getData('deal')); move(deal, stage); }}><header><strong>{stage.replaceAll('_', ' ')}</strong><span>{columns[stage]?.length || 0}</span></header>{(columns[stage] || []).map((deal) => <article className="deal-card" draggable key={deal.id} onDragStart={(event) => event.dataTransfer.setData('deal', JSON.stringify(deal))}><strong>{deal.title}</strong><span>{deal.Company?.name || 'Company'} · ${Number(deal.value || 0).toLocaleString()}</span><small>{deal.probability || 0}% probability</small></article>)}</section>)}</div></div>;
}

function PortalPage() {
  const [data, setData] = useState(null); const [error, setError] = useState('');
  useEffect(() => { void Promise.resolve().then(async () => { try { const result = await portalApi.getOverview(); setData(result.data); } catch (err) { setError(err.response?.data?.message || 'Portal access is unavailable.'); } }); }, []);
  if (error) return <div className="records-page"><div className="records-error">{error}</div></div>;
  if (!data) return <div className="records-page"><div className="records-state">Loading portal...</div></div>;
  return <div className="records-page"><div className="page-heading"><div><span className="page-kicker">Client Portal</span><h1>{data.client?.companyId ? 'Client workspace' : 'Portal'}</h1><p>Projects, requirements, invoices, and support tickets scoped to your client account.</p></div></div><div className="dashboard-grid"><div className="card"><h3>Projects</h3><p className="stat-number">{data.projects.length}</p></div><div className="card"><h3>Requirements</h3><p className="stat-number">{data.requirements.length}</p></div><div className="card"><h3>Invoices</h3><p className="stat-number">{data.invoices.length}</p></div><div className="card"><h3>Tickets</h3><p className="stat-number">{data.tickets.length}</p></div></div></div>;
}

export const DashboardPage = () => { const dispatch = useDispatch(); const navigate = useNavigate(); const { user } = useSelector((state) => state.auth); const [pageKey, setPageKey] = useState(window.location.hash.replace('#/', '') || 'dashboard'); useEffect(() => { const onHash = () => setPageKey(window.location.hash.replace('#/', '') || 'dashboard'); window.addEventListener('hashchange', onHash); return () => window.removeEventListener('hashchange', onHash); }, []); const active = items.some(([key]) => key === pageKey) ? pageKey : 'dashboard'; const open = (key) => { window.location.hash = `#/${key}`; }; const signOut = () => { dispatch(logout()); navigate('/login'); }; return <div className="dashboard-container"><nav className="navbar"><button className="navbar-brand" onClick={() => open('dashboard')}>DevFlow CRM</button><div className="navbar-menu"><span className="navbar-user">{user?.name || 'User'}</span><button onClick={signOut} className="btn-logout">Logout</button></div></nav><div className="dashboard-content"><aside className="sidebar"><ul className="sidebar-menu">{items.map(([key, label]) => <li key={key}><button onClick={() => open(key)} className={`menu-link ${active === key ? 'active' : ''}`}>{label}</button></li>)}</ul></aside><main className="main-content">{active === 'dashboard' ? <HomePage user={user} /> : active === 'deals' ? <DealsPipeline /> : active === 'portal' ? <PortalPage /> : active === 'requirements' ? <RequirementVaultPage /> : active === 'documents' ? <DocumentsPage /> : active === 'messages' ? <TicketConversationPage /> : active === 'taskwork' ? <TaskWorkspacePage /> : active === 'payments' ? <PaymentsPage /> : active === 'quotations' ? <QuotationsPage /> : <RecordsPage pageKey={active} />}</main></div></div>; };
export default DashboardPage;
