CREATE TABLE IF NOT EXISTS schema_migrations (version VARCHAR(255) PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW());

ALTER TABLE IF EXISTS clients ADD COLUMN IF NOT EXISTS "portalUserId" INTEGER REFERENCES users(id);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS "twoFactorEnabled" BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS two_factor_challenges (id SERIAL PRIMARY KEY, "userId" INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, "codeHash" VARCHAR(255) NOT NULL, "expiresAt" TIMESTAMPTZ NOT NULL, "consumedAt" TIMESTAMPTZ, "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(), "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS subtasks (id SERIAL PRIMARY KEY, "taskId" INTEGER NOT NULL REFERENCES tasks(id) ON DELETE CASCADE, title VARCHAR(255) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'todo', "assigneeId" INTEGER REFERENCES users(id), "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(), "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS task_comments (id SERIAL PRIMARY KEY, "taskId" INTEGER NOT NULL REFERENCES tasks(id) ON DELETE CASCADE, "authorId" INTEGER NOT NULL REFERENCES users(id), body TEXT NOT NULL, "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(), "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW());

INSERT INTO schema_migrations(version) VALUES ('001_remaining_platform_features') ON CONFLICT (version) DO NOTHING;
